

@url = https://n8ti6oe7w2.execute-api.eu-west-2.amazonaws.com/prod/
@token = eyJraWQiOiJ5NUV4Q3pyU3FPakl3RUsrOWFtem9nUXlcL0JCdUJhaXJvYklETEU3Umkraz0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiZTZmMzYzZjYtYjhmMy00MzA2LWI1NjYtNmExNjJhZDQ2ZTFmIiwic3ViIjoiMDZiMjgyODQtMTAzMS03MGFjLTMzYzQtNjEwMmY1MmY3ZjBkIiwiYXVkIjoiMTRwZjA2MzU5dG1jNnNnOXJiNnVoMGgybWwiLCJldmVudF9pZCI6ImRiMTY5NTk1LTJiNzYtNDRmMi1hYmE1LTQ4MTM4MmY0N2E5YSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzY3OTgyNDg1LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0yLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMl9xY3JzbDhhU2IiLCJjb2duaXRvOnVzZXJuYW1lIjoiQmF0bWFuIiwiZXhwIjoxNzY3OTg2MDg1LCJpYXQiOjE3Njc5ODI0ODUsImp0aSI6IjIwZDI0Yjc2LTBmYmYtNGU4MC1hYjI3LTdhYmMxNmYxMTI0MyJ9.O_11SDydwbEh-yWydJEx-LLO-eQITQiZBTWhCNAjWqvwNF5NWk74WoTakRVR7O47owN0FCBf1fxD0TpFoWAGV_HmshGOzuz9xjLLKhPD2UmrM2tVN6l7u8kvkClR7_G4CUsG9acnSabwbfrr-oggFp_SPEK234WAQZZsKOIAqjtlLYFgwXbX7hegyNS-nQOBS6nkaU7iMhI2_XmsVUQ8XF6vKyR5tlRupVelpbuY-pvkBjoC58b0_1GJXY_4Zwkxiyk4S2hKAdGI6V2e1FcdL2cgwDFXSJOGzddR1QW0BXZC6DJqh0_gMjYaAZFmdn-fZF8zI4XVW737bOMDNxcC8Q

GET {{url}}/movies
Authorization: Bearer {{token}}
###



POST {{url}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "title": "Black Panther 100",
  "year": "2025"
}
###




PUT {{url}}/movies?id=22e44f77-2fd5-45d5-9c3f-98419e683ba7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "year": "2000000000000001"
}
###



// now only admin can delete
//user must be autherised then admin to delete
DELETE  {{url}}/movies?id=22e44f77-2fd5-45d5-9c3f-98419e683ba7
Authorization: Bearer {{token}}
###




